### ISSUE TITLE
need tls termination design for CLI Service

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/kabanero-security#70]
The Kabanero CLI / REST service Route currently uses tls.termination: passthrough with unsigned certificates. We think it should be reencrypt , because if every service (landing, cli, what else?) uses passthrough they would each have unique certificate requirements.

Or, if customers require choice of passthrough, reencrypt, or edge then we need to know that as well.

These security choices should be made at install time for Kabanero as part of overall security certificate strategy and not as a unique experience for the CLI / REST service.

**Comment by chunlongliang-ibm** [comment]
I think re-encrypt is a better option, https://www.openshift.com/blog/self-serviced-end-to-end-encryption-approaches-for-applications-deployed-in-openshift

**Comment by davco01a** [comment]
This is going to have multiple parts to get to where we need to be. Rather than have OpenShift trust the self-signed cert that Liberty uses, we're going to have Liberty use a certificate generated by OpenShift.
Configure OpenShift to generate a certificate into the landing page pod. See https://docs.openshift.com/container-platform/4.2/authentication/certificates/service-serving-certificate.html. For an example of how we did this with kabanero-eventing, see https://github.com/kabanero-io/kabanero-operator/blob/master/config/orchestrations/events/0.1/kabanero-events.yaml.
Convert the certificate to a keystore. See https://developers.redhat.com/blog/2017/11/22/dynamically-creating-java-keystores-openshift/. The certificate from step 1 should be mounted in the file system and we should use the keytool command to create a keystore from it. We will need to consider what container should build the keystore. We could use an init container as the example does, or do it right in the main container before we start Liberty. If we do it in the init container we must choose carefully what image we use, or build our own. The UBI base image (but not UBI-min) has openSSL, and the landing page image should have keytool I think but someone would need to verify that.
Update the liberty configuration for the landing page to use the keystore that was built in step 2. This probably ends up being the easiest part :-)
Red Hat DeveloperRed Hat Developer
Dynamically Creating Java Keystores in OpenShift - Red Hat Developer
Introduction With a simple annotation to a service, you can dynamically create certificates in OpenShift. Certificates created this way are in PEM (base64-encoded certificates) format and cannot be directly consumed by Java applications, which need certificates to be stored in Java KeyStores. In this post, we are going to show a simple approach to enable …

**Comment by davco01a** [comment]
Above to get cert setup to pass on down to CLI client

**Comment by kaczyns** [comment]
The work to convert the landing page to use a service serving certificate was done in kabanero-io/kabanero-operator#178.  There are three PRs there, two for operator and one for landing page.  You should be able to use the same pattern for the CLI service.

Using this model, the certificate presented to external clients (web browsers) is not the service serving certificate, but instead the "edge certificate"  (default ingress certificate?) and may already be trusted by browsers in some environments (ie IBM Cloud).

Please take a look at what we did in 178 so that we don't re-invent the wheel here unless we have to.

**Comment by kaczyns** [comment]
Had a call with @davco01a @tseelbach @s1cyan @mezarin today.
We agreed that a route with `re-encrypt` is the way to go.  Dave opened kabanero-io/kabanero-operator#645 and the kab operator will:
* Modify the route for the CLI service to use re-encrypt
* Generate a PKCS12 file that the CLI service can use in place of a self-signed certificate

The CLI service will need to:
* Edit the Liberty server's `server.xml` to point to the new PKCS12 keystore

This is identical to what we did for the landing page, and the details can be seen in issue kabanero-io/kabanero-operator#178.

**Comment by tseelbach** [comment]
This issue is closed by https://github.com/kabanero-io/kabanero-operator/issues/674 as well as https://github.com/kabanero-io/kabanero-operator/issues/645 
**Design:**
The best "Design" description  is the following copy/paste of Tim's note in PR https://github.com/kabanero-io/kabanero-operator/pull/680

I removed the key/certificate from the reencrypt route for the landing page and CLI service. They were specified incorrectly. Those parameters identify the route to the external caller. We want the external caller to see the default ingress certificate. To get that behavior, we should not be specifying the key/certificate on the route.
The internal (route -> pod) connection uses a service serving certificate. The doc that I could find says that when you use reencrypt you have to provide the CA that signed the certificate in the pod, in the route's configuration. However it appears that OpenShift implicitly trusts the service serving certificate CA. This must be true, because the existing configuration did not supply a destination CA certificate, and everything worked fine. So the route now has no certificates or keys in it. This means that all of the code that reads the CA/certificate and encodes/decodes it, is deleted.
I added the config to the route that converts http->https at @davco01a 's request.
I tested connectivity between my browser and the landing page / CLI service, and I am presented with the ingress certificate, as we expect.

**Comment by tseelbach** [comment]
@jtmulvey @kaczyns do we need to add a line in the Kabanero CR documentation, or somewhere else, that the landing and CLI services use default ingress TLS cert?

**Comment by chunlongliang-ibm** [comment]
If we do not offer an option to customize route certificate, I suggest that we do not document it. By default all *.apps subdomain use ingress default certificate. If we have option to change route certificate, we should mention it, so user knows how to customize route certificate.

**Comment by marikaj123** [comment]
@chunlongliang-ibm - Keeping this issue in the backlog and moving it out from Kabanero release 0.9.
